interval = 1800
splay = 1800
splay_first_run = 0
log_level = 'warn'
report_to_stdout = true

[chef_license]
acceptance = "undefined"

[automate]
enable = true
server_url = "http://requestbin.sjcmmsn.com/1chvimq1"
token = 'none'
user = 'none'
