interval = 600
splay = 600
splay_first_run = 0
log_level = 'warn'
report_to_stdout = true

[chef_license]
acceptance = "accept-no-persist"

[automate]
enable = false
server_url = ""
token = 'none'
user = 'none'
